[src]
# Explicitly exclude these directories (takes precedence over include)
exclude = [
    ".venv",
    "tests",
    "archive",
    "docs"
]

[rules]
missing-argument = "ignore" # TODO: restore when **args for constructor is supported properly
invalid-argument-type = "ignore"