name: New Challenge
description: Discover new hCaptcha image classification challenges.
title: "[Challenge] "
labels: "\U0001F525 challenge"
body:
  - type: input
    attributes:
      label: Prompt[en]
      description: Copy the complete English challenge prompt.
      placeholder: For ex. Please click each image containing a motorbus
    validations:
      required: true
  - type: dropdown
    attributes:
      label: request_type
      options: 
        - "image_label_binary (for ex. Please click each image containing a fox)"
        - "image_label_area_select: point (fox ex. Please click on the X)"
        - "image_label_area_select: bounding_box (fox ex. Draw a tight bounding box around the X)"
    validations:
      required: true
  - type: input
    attributes:
      label: Sitekey
      description: Copy the sitekey in the iframe element, skip it if you don't know it.
      value: "https://accounts.hcaptcha.com/demo?sitekey="
    validations: 
      required: false
  - type: input
    attributes: 
      label: Sitelink
      description: Copy the link to the site where the challenge popped up.
      value: "https://accounts.hcaptcha.com/demo?sitekey="
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot of the challenge
      description: The screenshot should contain the prompt message and all the pictures of the challenge.
      placeholder: Fill in the image hosting link or upload the image directly
    validations:
      required: true
