name: hCAPTCHA Collector

on:
  issues:
    types:
      - opened
  push:
    branches:
      - ci-collector
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - ".deepsource.toml"
      - "src/**"
  workflow_dispatch:

  # “At minute 7 past every 2nd hour.”
  schedule:
    - cron: "7 */2 * * *"

jobs:
  setup:
    env:
      GITHUB_TOKEN: ${{ secrets.SENTINEL_ACCESS_TOKEN }}
      COLLECTOR_PER_TIMES: 20
      COLLECTOR_LOOP_TIMES: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -U hcaptcha-challenger[sentinel]
          playwright install chromium
          playwright install-deps chromium
      - name: Startup sentinel
        run: |
          cd automation && python3 collector.py
