name: hCAPTCHA Collector

on:
  workflow_dispatch:

  # https://crontab.guru/
  schedule:
    - cron: "37 */2 * * *"

jobs:
  setup:
    env:
      GITHUB_TOKEN: ${{ secrets.SENTINEL_ACCESS_TOKEN }}
      SITEKEY_EPIC: 91e4137f-95af-4bc9-97af-cdcedce21c8c
      COLLECTOR_PER_TIMES: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout environment
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -U hcaptcha-challenger[sentinel]
          playwright install chromium
          playwright install-deps chromium
      - name: Startup collector
        continue-on-error: true
        timeout-minutes: 20
        run: |
          cd automation && python3 collector.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: tmp_dir
          path: ./automation/tmp_dir
